# Configs

title: "Anisha Jain"
name: "Profile for Anisha Jain"
email: jainanisha18@gmail.com
url: "https://AnishaJain41.github.io"
baseurl: "/Anisha-Jain-Profile"
repository: "AnishaJain41/Anisha-Jain-Profile"
header:
  image: assets/images/24-Anisha_Jain-1107-WD-07.jpg

include:
  - _pages
  - assets
  - index.html
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast"

# settings for author profile
author:
  name   : "Anisha Jain"
  avatar : "/assets/images/24-Anisha_Jain-1107-WD-07.jpg"
  bio    : "Anisha is a PhD Candidate in Economics at Northern Illinois University and a Data Analyst at the Workforce and Organizational Research Centre (WORC). Specializing in labor economics and econometrics, Anisha's current research investigates the dynamics of labor productivity and its relationship to compensation, capital intensity, and intermediate inputs. With a rigorous quantitative background, Anisha is dedicated to advancing understanding in productivity and labor market outcomes."
  location: "DeKalb, Illinois"
  github : 
  linkedin: "anisha-jain41" #This is a fake site that won't work. To add your own, make sure to include just the profile, not the full url. Eg. anna-klis-1337a150
  email  : jainanisha18@gmail.com


# # comments by disqus
#comments:
  #provider: "disqus"
  #disqus:
    #shortname: "pwills-com"

#analytics:
  #provider: "google"
  #google:
    #tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
